version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: aljazara_database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file: .env

  directus:
    image: directus/directus:11.13.0
    container_name: directus
    restart: always
    depends_on:
      - postgres
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/directus_data:/directus/database
    env_file: .env
