services:
  postgres:
    image: postgres:17
    container_name: aljazara_database
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file: .env

  directus:
    image: directus/directus:11.13.0
    container_name: directus
    depends_on:
      - postgres
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/directus_data:/directus/database
    env_file: .env

  nginx:
    depends_on:
      - directus
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
      - ./tls/dhparam:/etc/nginx/dhparam

      - ./tls/aljazara/conf:/etc/nginx/ssl/aljazara
      - ./tls/aljazara/data:/usr/share/nginx/html/letsencrypt/aljazara

      - ./tls/www-aljazara/conf:/etc/nginx/ssl/www-aljazara
      - ./tls/www-aljazara/data:/usr/share/nginx/html/letsencrypt/www-aljazara

      - ./tls/app-aljazara/conf:/etc/nginx/ssl/app-aljazara
      - ./tls/app-aljazara/data:/usr/share/nginx/html/letsencrypt/app-aljazara
